#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Object-Signature
Version  : 1.07
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Object-Signature-1.07.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Object-Signature-1.07.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libo/libobject-signature-perl/libobject-signature-perl_1.07-2.debian.tar.xz
Summary  : 'Generate cryptographic signatures for objects'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-2.0
Requires: perl-Object-Signature-license
Requires: perl-Object-Signature-man
Requires: perl(Module::Install::DSL)
BuildRequires : perl(Module::Install::DSL)

%description
NAME
Object::Signature - Generate cryptographic signatures for objects
SYNOPSIS
# In your module
package My::Module
use base 'Object::Signature';

# In outside code
my $Object = My::Module->new;
print "Object Signature: " . $Object->signature;

%package license
Summary: license components for the perl-Object-Signature package.
Group: Default

%description license
license components for the perl-Object-Signature package.


%package man
Summary: man components for the perl-Object-Signature package.
Group: Default

%description man
man components for the perl-Object-Signature package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Object-Signature-1.07
mkdir -p %{_topdir}/BUILD/Object-Signature-1.07/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Object-Signature-1.07/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Object-Signature
cp LICENSE %{buildroot}/usr/share/doc/perl-Object-Signature/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Object/Signature.pm
/usr/lib/perl5/site_perl/5.26.1/Object/Signature/File.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Object-Signature/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Object::Signature.3
/usr/share/man/man3/Object::Signature::File.3
